name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'v0.116.1'
          extended: true

      - name: Build
        run: hugo --minify
        env:
          HUGO_disqusShortname: ${{ secrets.HUGO_disqusShortname }}
          HUGO_PARAMS_FIREBASE_APIKEY: ${{ secrets.HUGO_PARAMS_FIREBASE_APIKEY }}
          HUGO_PARAMS_FIREBASE_APPID: ${{ secrets.HUGO_PARAMS_FIREBASE_APPID }}
          HUGO_PARAMS_FIREBASE_AUTHDOMAIN: ${{ secrets.HUGO_PARAMS_FIREBASE_AUTHDOMAIN }}
          HUGO_PARAMS_FIREBASE_MEASUREMENTID: ${{ secrets.HUGO_PARAMS_FIREBASE_MEASUREMENTID }}
          HUGO_PARAMS_FIREBASE_MESSAGINGSENDERID: ${{ secrets.HUGO_PARAMS_FIREBASE_MESSAGINGSENDERID }}
          HUGO_PARAMS_FIREBASE_PROJECTID: ${{ secrets.HUGO_PARAMS_FIREBASE_PROJECTID }}
          HUGO_PARAMS_FIREBASE_STORAGEBUCKET: ${{ secrets.HUGO_PARAMS_FIREBASE_STORAGEBUCKET }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
